### ISSUE TITLE
HTTP retries

### ISSUE THREAD

**Issue by tjkirch** [awslabs/tough#12]
On connection resets, the `Read`er should retry the HTTP connection for the rest of the range (similar to wget’s default behavior).

**Comment by webern** [comment]
Given some recent issues, we will prioritize this. However, reqwest [doesn't offer a suitable interface for this](https://github.com/seanmonstar/reqwest/issues/316):

> retry the HTTP connection for the rest of the range (similar to wget’s default behavior).

But we can at least start over from the beginning, which is what I will implement quickly.

**Comment by iliana** [comment]
We return an `impl Read` — if we start over and then continue sending those bytes to the reader, the data is corrupt.

We can keep a counter of bytes read so far and set [a `Range` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) pretty trivially. We would have to use a wrapper struct around a `reqwest::Response`. We could also keep a counter of bytes and skip the first `n` bytes on the resulting Read stream.

Either way, we need a wrapper struct to *correctly* impl Read while possibly re-sending HTTP requests on retriable errors.
