### ISSUE TITLE
Deprecate `tuftool refresh`

### ISSUE THREAD

**Issue by zmrow** [awslabs/tough#140]
I agree with @tjkirch but also think that deprecating/removing the `refresh` command can be done in a separate pull request.

_Originally posted by @iliana in https://github.com/awslabs/tough/pull/139#issuecomment-640924495_

**Comment by zmrow** [comment]
Originally requested by @tjkirch in [139](https://github.com/awslabs/tough/pull/139#pullrequestreview-426638863)

>After looking at this again, I have to ask - are we sure this should be a separate subcommand? It's >basically refresh plus adding targets. I think it'd make sense to me to remove refresh, and have >the targets in update be optional... (refresh and update mean basically the same here...)

>It's also quite similar to create, just with a from_repo instead of a new...

**Comment by zmrow** [comment]
[Suggestion for interface](https://github.com/awslabs/tough/pull/139#issuecomment-640959183) by @tjkirch 

How about:
`tuftool repo --output-dir bar --input-dir foo --add-targets` = `update`
`tuftool repo --output-dir bar                           --add-targets` = `create`
`tuftool repo --output-dir bar --input-dir foo                         ` = `refresh`

Obviously output directory is always required, so it could be positional, but I guess I'm biased toward "options".

**Comment by zmrow** [comment]
> [Suggestion for interface](https://github.com/awslabs/tough/pull/139#issuecomment-640959183) by @tjkirch
> 
> How about:
> `tuftool repo --output-dir bar --input-dir foo --add-targets` = `update`
> `tuftool repo --output-dir bar --add-targets` = `create`
> `tuftool repo --output-dir bar --input-dir foo ` = `refresh`
> 
> Obviously output directory is always required, so it could be positional, but I guess I'm biased toward "options".

I like the idea of a `repo` subcommand to unify some of these steps. However from your example above, a user would need to know just the right incantation of arguments to get the output they desire. 

Here is a summary of the arguments:

### `create` / `update` / `refresh`
* `output-dir` : where to write the repo
* `root` : where to find `root.json`
* `keys` : signing keys
* `snapshot / targets / timestamp version` : metadata version
* `snapshot / targets / timestamp expires` : metadata expiration

### `refresh` / `update`
* `metadata_base_url` : URL for the existing repo's metadata

### `create` / `update`
* `targets-dir` : where to find new targets
* `jobs` : number of hashing threads to use (if not using the default)
* `follow` : follow symlinks in the `targets-dir`

**Comment by zmrow** [comment]
I don't think we gain very much by trying to merge `create / update / refresh` under one roof and end up making the code's argument parsing harder to follow.

If we really feel the need to unify `update` and `refresh`, my vote is for @tjkirch 's suggestion in #139 . We'd end up with

`tuftool create --args-here`
`tuftool update --args-here`

Using this approach, you still end up with a few arguments that won't be used in the case of a "refresh": `jobs`, `follow`, and whatever the `targets-dir` ends up being called.

**Comment by tjkirch** [comment]
After sleeping on it, I agree, I don't think it makes sense to combine create and update.  I do think update and refresh are too similar, though, and having `--add-targets DIR` be the difference makes sense to me.

So, my vote:
`tuftool create <args same as now>`
`tuftool update <args same as refresh is now> --add-targets DIR [ --jobs N ]`
~~`tuftool refresh`~~
