### ISSUE TITLE
tuftool: download should support file://

### ISSUE THREAD

**Issue by iliana** [awslabs/tough#222]
This is incredibly useful for testing, so let's just make it work :)

**Comment by nealmcb** [comment]
Note that tuftool update already supports file:// as seen in the example in the README.md.

**Comment by iliana** [comment]
Yep, I think it's a mismatch in our code between use of `Repository` for `download` and `RepositoryEditor` for `update`.

**Comment by srgothi92** [comment]
Fixed in #252
