### ISSUE TITLE
tuftool: Wire up `ExpirationEnforcement::Unsafe`

### ISSUE THREAD

**Issue by iliana** [awslabs/tough#224]
To assist with updating expired repositories, we should provide an option to flip the `ExpirationEnforcement` enum if needed.

**Comment by srgothi92** [comment]
I am thinking of adding additional flag `--unsafe true` to support this in `tuftool update` and `tuftool download` command. By default the value of `--unsafe` would be `false`.

Should we support this flag in `delegated targets` too ? If yes, I will create another issue for that.

**Comment by tjkirch** [comment]
Maybe something like `--allow-expired-repo` would be clearer than `unsafe`?

**Comment by srgothi92** [comment]
Fixed in #254
