### ISSUE TITLE
Move signing functionality out of `tuftool`

### ISSUE THREAD

**Issue by zmrow** [awslabs/tough#26]
Currently the ability to sign metadata lives in `tuftool/src/key.rs`. This functionality probably belongs in the `tough` library.

**Comment by iliana** [comment]
The signing implementation should probably not be limited to in-memory keys, since I'll want to add support for [asymmetric KMS keys](https://aws.amazon.com/blogs/security/digital-signing-asymmetric-keys-aws-kms/).
