### ISSUE TITLE
replicate ci locally with script or make

### ISSUE THREAD

**Issue by webern** [awslabs/tough#266]
Whenever I work on the project, I end up doing a find and replace of the github actions file to produce a script that does the same locally so that I can run all the CI stuff locally instead of waiting for CI to tell me what clippy wants or whatever.

We could add a script or a makefile to make that easier. Downside: it would have to be maintained along with the GitHub actions yaml since it would likely *not* be used by the CI.

**Comment by samuelkarp** [comment]
It might be easier if we make sure that each of the GitHub actions steps is just a call to that script/makefile; then we only have to maintain it one place and you can inspect that what GitHub actions is doing is the same as what you're doing locally.
