### ISSUE TITLE
"tough" doesn't compile on windows

### ISSUE THREAD

**Issue by Cytro54** [awslabs/tough#343]
Hi, (sry, this is my first pull request on any open source project ever)

I was looking for a TUF implementation in rust, and this crate suits my needs, but it doesn't compile on Windows, so I've done a little patch to make it work on this OS. 

It re-implements the functions `SignedRepository::link_target`, `SignedDelegatedTargets::link_target` and `FilesystemTransport::fetch` when the `target_os="windows"` to make them work on Windows.

This patch doesn't break (more) tests : when testing on my side (without the patch), all tests passed expect test_expiration_enforcement_unsafe on WSL/Ubuntu 18.04 LTS, it does the same under Windows and WSL with the patch applied.

I've linked a PR   #https://github.com/awslabs/tough/pull/342

**Comment by gregdek** [comment]
Thanks for this! The team will take a look and get back in touch soon if we have questions.

**Comment by Cytro54** [comment]
Well , the first commit for the `tough` crate was merged; I think that we can close this issue, Windows is now partially supported ^^
