### ISSUE TITLE
tuftool command to update metadata with new root.json file

### ISSUE THREAD

**Issue by arnaldo2792** [awslabs/tough#478]
**Problem**

Whenever a new `root.json` file is created, the metadata in existing tuf repositories must be updated as well. The brute force process of doing so is as follows:

- Iterate through all the tuf repositories
- Pull down the targets for each repository
- Run `tuftool update <>` for each repository
- Push update the remote repositories with new metadata

In repositories where the targets' sizes are substantial, this process could take a very long time. If the targets haven't change, it should be possible to reuse an existing, unexpired, trusted `targets.json` file to generate a new `targets.json` using the newly created `root.json`.

**Proposal**

There could be a new command with the following shape, that generates new metadata from existing, unexpired, trusted metadata:

```bash
tuftool create-metadata \
    --key <publication-key> \
    --current-root <path-to-existing-root.json> \
    --new-root <path-to-new-root.json> \
    --metadata-url <url-to-repo> \
    --outdir <output-directory> \
    --timestamp-expires '<>' \
    --snapshot-expires '<>'
```

Both `root.json`s files are required to 1) verify the existing metadata, and 2) generate the new metadata

**Comment by stmcginnis** [comment]
Just to capture this somewhere, I have heard some feedback that `update-metadata` seems more logical to some folks. I was also thinking something like `transfer-metadata` or `forward-metadata` might make more sense and make it more clear that the command is taking existing metadata from a previous root (`--current-root`) and transferring that metadata to be included in the new root (`--new-root`).

Feedback welcome, but also just didn't want to forget about this if the discussion comes up in the future.
