### ISSUE TITLE
Update Clap to v4

### ISSUE THREAD

**Issue by webern** [awslabs/tough#526]
Looks like clap major version bump causes compilation errors. Update clap from 3 to 4.

_Originally posted by @webern in https://github.com/awslabs/tough/issues/525#issuecomment-1276741808_

**Comment by webern** [comment]
Closing as dup of #529

**Comment by stmcginnis** [comment]
> Closing as dup of https://github.com/awslabs/tough/issues/529

Actually closing now. ;)
