### ISSUE TITLE
Surface a `version` subcommand

### ISSUE THREAD

**Issue by jpmcb** [awslabs/tough#608]
It would be great to have a `version` subcommand so I can know which version of `tuftool` I have:
```
bash-4.2$ tuftool --help
tuftool
This wrapper enables global options and initializes the logger before running any subcommands

USAGE:
    tuftool [OPTIONS] <SUBCOMMAND>

OPTIONS:
    -h, --help                     Print help information
    -l, --log-level <log-level>    Set logging verbosity [trace|debug|info|warn|error] [default:
                                   info]

SUBCOMMANDS:
    clone         Clone a TUF repository, including metadata and some or all targets
    create        Create a TUF repository
    delegation    Delegation Commands
    download      Download a TUF repository's targets
    help          Print this message or the help of the given subcommand(s)
    root          Manipulate a root.json metadata file
    update        Update a TUF repository's metadata and optionally add targets
```

**Comment by webern** [comment]
Weird. I think updating to Clap is the answer. Also, personally I hate `version` as a subcommand, which is a go thing, and prefer `--version` which seems like the old school way.

**Comment by webern** [comment]
Weird I didn't realize we are already using clap, see #526, #529. I expected Clap to do this for us by default.

**Comment by jpmcb** [comment]
Whatever works! `--version` is a good option too

**Comment by cbgbt** [comment]
Based on [the example from the docs](https://docs.rs/clap/4.4.0/clap/index.html#example) I think we just need to add a `#[command]` attribute to the arguments struct which specifies to generate a `--version` implementation.
